In [ ]:
import pandas as pd

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
df.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [ ]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
df_clean = df.rename(columns={'race/ethnicity': 'ace_ethnicity', 'parental level of education': 'parental_level_f_education', 'test preparation course': 'test_preparation_course',
                   'math score': 'math_score', 'reading score': 'reading_score', 'writing score': 'writing_score'})

In [ ]:
df_clean.head()

,gender,ace_ethnicity,parental_level_f_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
df_clean.to_csv("students_clean.csv")

Pandas (20 задач)

In [ ]:
df = pd.read_csv("students_clean.csv")

NameError: name 'pd' is not defined

In [ ]:
df.head()

,Unnamed: 0,gender,ace_ethnicity,parental_level_f_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,0,female,group B,bachelor's degree,standard,none,72,72,74
1,1,female,group C,some college,standard,completed,69,90,88
2,2,female,group B,master's degree,standard,none,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,47,57,44
4,4,male,group C,some college,standard,none,76,78,75

In [ ]:
df['ace_ethnicity'].unique()

array(['group B', 'group C', 'group A', 'group D', 'group E'],
      dtype=object)

In [ ]:
df['ace_ethnicity'].nunique()

5

In [ ]:
df['math_score']

NameError: name 'df' is not defined

In [ ]:
df = pd.read_csv("students_clean.csv")

NameError: name 'pd' is not defined